@startuml
skinparam actorStyle awesome
autonumber

actor "Пользователь" as User
participant "Telegram API / Bot" as TG

box App
participant "Frontend (Svelte)" as Front
participant "Backend (API)" as Back
database "DB" as db
end box

== Инициация оплаты ==

User -> Front : Нажимает "Оплатить"
Front -> Back : POST /api/payment/invoice (slug)
Back -> TG : createInvoiceLink (название, цена, payload)
TG --> Back : https://t.me/$invoice_link
Back --> db++: Сохранить в user_subscriptions(paidUntil, techId, userId, status: 'pending')
db -> Back--: 
Back --> Front : { paymentUrl, orderId }

== Процесс оплаты ==

Front -> User : Перенаправляет по paymentUrl (или Telegram.openInvoice)
User -> TG : Вводит данные / подтверждает звездами
TG -> User : Показывает "Оплата прошла успешно"

== Обработка результата (Webhook) ==

TG -> Back : POST /api/payment/webhook (Successful Payment)
note right: Telegram сообщает серверу,\nчто деньги списаны
Back -> db : Обновляет статус заказа в БД (paid: true)\nДобавляет технику в список юзера(user_subscriptions(status: 'paid'))

== Проверка статуса (Polling) ==

loop Каждые 2-3 секунды (до успеха или таймаута)
    Front -> Back : GET /api/payment/check-status (orderId)
    Back --> Front : { status: "paid" }
end

== Финал ==

Front -> Front : Остановка спиннера (isChecking = false)
Front -> User : Показывает конфетти / успех
Front -> Front : Обновляет purchasedSlugs и закрывает Paywall

@enduml